const typeRedux = {
  FETCH_SEARCH_USER: 'FETCH_SEARCH_USER',
  FETCH_RANDOM_USER: 'FETCH_RANDOM_USER',
  FETCH_LOGIN_USER: 'FETCH_LOGIN_USER',
  FETCH_LOGOUT_USER: 'FETCH_LOGOUT_USER',
  FETCH_SIGNUP_USER: 'FETCH_SIGNUP_USER',
  FETCH_SEARCH_PASSION: 'FETCH_SEARCH_PASSION',
  FETCH_SEARCH_HISTORY: 'FETCH_SEARCH_HISTORY'
};

export default typeRedux;
